[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.xml",
  "php82Extensions.curl"
]

[phases.build]
cmds = [
  "cp .env.example .env",                        # ✅ ينسخ .env.example إلى .env
  "composer install --no-dev --optimize-autoloader",
  "php artisan key:generate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
