[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
]

[phases.build]
cmds = [
  # نسخ ملف .env إذا لم يكن موجودًا
  "test -f .env || cp .env.example .env",

  # تثبيت الـ dependencies
  "composer install --no-dev --optimize-autoloader",

  # إنشاء APP_KEY بعد التأكد من وجود .env و vendor
  "php artisan key:generate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
