[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "nodejs_20"
]

[phases.build]
cmds = [
  # نسخ ملف .env إذا لم يكن موجودًا
  "if [ ! -f .env ]; then cp .env.example .env; fi",

  # تثبيت مكتبات PHP
  "composer install --no-dev --optimize-autoloader",

  # توليد مفتاح التطبيق
  "php artisan key:generate --force",

  # تنفيذ الترحيلات، لو فشلت كمل بدون توقف
  "php artisan migrate --force || echo 'Migration failed, continuing...'",

  # تثبيت مكتبات npm (إن وجد ملف package.json)
  "if [ -f package.json ]; then npm ci; fi",

  # تجميع ملفات الواجهة (اختياري)
  "if [ -f vite.config.js ]; then npm run build; fi"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
